### ISSUE TITLE
ASD version is wrong

### ISSUE THREAD

**Issue by Ambrevar** [nsrahmad/cl-rss#1]
According to the changelog, it should be 0.9.1.

**Comment by nsrahmad** [comment]
Hi, This is not the official repository for cl-rss. It is just a fork I made to quickly make some local changes (I didn't even push my local changes). For now, I have pulled from the original source http://git.kpe.io/?p=cl-rss.git;a=summary , which did address this issue. 

For any further issues or patches, please contact Author on the e-mail address mentioned in the ASD file.

**Comment by Ambrevar** [comment]
Acknowledged, thanks!
